### ISSUE TITLE
How about adding pandas to the requirements.txt?

### ISSUE THREAD

**Issue by MonEstCha** [jftsang/pypew#55]
If pandas is not installed, some tests are not run and the selection fields do not display any options. Adding pandas to requirements.txt would solve those problems.

**Comment by jftsang** [comment]
I removed pandas because it was quite large and it wasn't necessary for 
something for most stuff. I believe it's only used for reading a CSV 
file somewhere, which we can probably do without Pandas?

-- 
J. M. F. Tsang

Please note, I may occasionally send mail outside of ordinary working 
hours, but I do not expect you to reply out of ordinary working hours.

**Comment by MonEstCha** [comment]
It's also required for running all tests in the TestModels class and to load hymn information (see get_neh_df() in file utils.py).
